# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='shopping.Product_unit'),
        ),
    ]
