# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-06 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20160505_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('no aprobado', 'No aprobado'), ('entregado', 'Entregado'), ('en curso', 'En curso')], default='en curso', max_length=11),
        ),
    ]
