# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-07 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_auto_20160506_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='aproved_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('en curso', 'En curso'), ('no aprobado', 'No aprobado'), ('entregado', 'Entregado'), ('aprobado', 'Aprobado')], default='en curso', max_length=11),
        ),
    ]
