# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-07 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20160507_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='aproved_date',
            new_name='approved_date',
        ),
        migrations.AddField(
            model_name='product',
            name='number_sales',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
