# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-08 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_product_unit_subtotal_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_unit',
            name='subtotal_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
