# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-08 02:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_auto_20160508_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
